---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: htb
replicas:
  - name: kali
    count: 1
resources:
  - ../../../base/default
  - namespace.yaml
  - volume.yaml
  - secrets.enc.json
