apiVersion: apps/v1
kind: Deployment
metadata:
  name: c2
  labels:
    app: c2
spec:
  replicas: 0
  selector:
    matchLabels:
      app: c2
  template:
    metadata:
      labels:
        app: c2
    spec:
      volumes:
        - name: htb-st
          persistentVolumeClaim:
            claimName: htb-cl
      containers:
        - name: c2
          securityContext:
            privileged: true
            runAsUser: 0
          image: oonray/c2:v1.0.91
          volumeMounts:
            - mountPath: /root/htb/
              name: htb-st
          ports:
            - containerPort: 5000
            - containerPort: 31337
            - containerPort: 8080
            - containerPort: 443
