kind: ConfigMap
metadata:
  name: opnevpn-script
apiVersion: v1
data:
  route-override.sh: |-
    #!/bin/sh
    VPN_GATEWAY=$(route -n | awk 'NR==3' | awk '{ print $2 }')
    ip route del 0.0.0.0/1 via $VPN_GATEWAY
    echo "Route Updated"
