apiVersion: v1
kind: PersistentVolume
metadata:
  name: htb-pv
  namespace: htb
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/e/htb/startingpoint"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: htb-cl
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
