version: "3"
services:
  vpn:
    image: oonray/vpn:v1.1.43
    stdin_open: true
    tty: true
    network_mode: "host"
    cap_add: ["NET_ADMIN","NET_RAW"]
    volumes:
      - ~/htb:/root
