apiVersion: apps/v1
kind: Deployment
metadata:
  name: kali
spec:
  template:
    spec:
      hostAliases:
        - ip: 10.90.60.80
          hostnames:
            - foophonesels.com
      volumes:
        - name: pass-config
          secret:
            secretName: vpn-config
            items:
              - key: pass.txt
                path: pass.txt
        - name: danted
          configMap:
            name: dante
            items:
              - key: danted.conf
                path: danted.conf
      containers:
        - name: openvpn
          volumeMounts:
            - mountPath: /opt/pass.txt
              name: pass-config
              subPath: pass.txt
            - mountPath: /etc/danted.conf
              name: danted
              subPath: danted.conf
