apiVersion: v1
kind: Service
metadata:
  name: c2
spec:
  type: NodePort
  selector:
    app: c2
  ports:
    - name: "sliver"
      protocol: TCP
      port: 31337
      targetPort: 31337
    - name: "empire"
      protocol: TCP
      port: 1337
      targetPort: 1337
    - name: "starkille"
      protocol: TCP
      port: 5000
      targetPort: 5000
