---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: htb
images:
  - name: kali
    newTag: latest
  - name: vpn
    newTag: v1.0.86
resources:
  - services/vpn.yaml
  - deployments/kali.yaml
