---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: htb
replicas:
  - name: kali
    count: 1

namePrefix: machines-

labels:
  - pairs:
      vpn: machines

resources:
  - secrets.tmpl.yaml
  - https://github.com/oonray/k8sHTB.git

replacements:
  - source:
      kind: Secret
      name: machines-vpn-config
      fieldPath: metadata.name
    targets:
      - select:
          kind: Deployment
          name: kali
        fieldPaths:
          - spec.template.spec.volumes.[name=vpn-config].secret.secretName
  - source:
      kind: Service
      name: machines-kali-service
      fieldPath: metadata.name
    targets:
      - select:
          kind: IngressRoute
        fieldPaths:
          - spec.routes.[kind=Rule].services.[name=kali-service].name

patches:
  - target:
      kind: IngressRoute
    patch: |
      - op: replace
        path: /spec/routes/0/match
        value: "Host(`machines.kali.example.com`)"
  - target:
      kind: IngressRoute
      name: web-kali-ingress
    patch: |
      - op: replace
        path: /spec/routes/0/match
        value: "Host(`proxy.machines.kali.example.com`)"
      - op: replace
        path: /spec/routes/1/match
        value: "Host(`web.machines.kali.example.com`)"
